name: sops

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]    
    paths:
      - 'sops/*'
      - '.github/workflows/sops.yml'
  workflow_dispatch:

env: 
  REGISTRY_PATH: 'docker.io/paritytech'
  IMAGE_NAME: 'sops'
  SOPS_VERSION: "3.9.0"
  VAULT_VERSION: "1.17.3"

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: set vars
      id: vars
      run: |
        export COMMIT_SHA=${{ github.sha }}
        echo "IMAGE_DATE_TAG='${COMMIT_SHA:0:8}-$(date +%Y%m%d)'" >> $GITHUB_OUTPUT  

    - name: build and push staging
      if: ${{ github.event_name == 'pull_request' }}
      uses: ./.github/actions/build-push-image      
      with:
        registry: ${{ env.REGISTRY_PATH }}
        image-name: ${{ env.IMAGE_NAME }}
        image-tags: >
          staging
        build-args: |
          SOPS_VERSION='${{ env.SOPS_VERSION }}'
          VAULT_VERSION='${{ env.VAULT_VERSION }}'

    - name: build and push
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: ./.github/actions/build-push-image      
      with:
        registry: ${{ env.REGISTRY_PATH }}
        image-name: ${{ env.IMAGE_NAME }}
        image-tags: >
          ${{ env.SOPS_VERSION }}
          latest
        build-args: |
          SOPS_VERSION='${{ env.SOPS_VERSION }}'
          VAULT_VERSION='${{ env.VAULT_VERSION }}'